[package]
name = "patch-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
byteorder = "1.4.3"
clap = { version = "4.1.4", features = ["derive"] }
crc32fast = "1.3.2"
num_enum = "0.6.0"
thiserror = "1.0.38"
